### ISSUE TITLE
ngnix container failed to start

### ISSUE THREAD

**Issue by rsalevsky** [dockhippie/php#4]
docker[11040]: nginx: [emerg] invalid number of arguments in "worker_processes" directive in /etc/nginx/nginx.conf:7

I also tried to set the env variable but with the same result.

**Comment by tboerger** [comment]
https://github.com/dockhippie/php/blob/master/nginx/rootfs/etc/s6/nginx/setup#L3 the template engine uses the wrong env variable prefix. I will submit a fix.

**Comment by tboerger** [comment]
Fixed via 6df7111e4656e2b890095bad0457866036b78f8f, just need to wait for getting the build on the docker hub done.
